### PR TITLE
add "Homepage" field to cabal file

### PR DESCRIPTION
**Pull request by chris-martin**
Sorry to bother you on an old project, but currently there's no link to this repo from [Hackage](https://hackage.haskell.org/package/pam) and I'm hoping we can fix that :)

### CODE REVIEW

**Comment by chris-martin** [comment]
I'm probably going to do some more work on this library. Do you still have any interest in maintaining it if I submit some other, less trivial, pull requests? If not, would you mind letting me take over as a maintainer?

**Comment by etarasov** [comment]
Hi Chris!

Please take over as a maintainer, I already forgot how to C. Is there anything I should do for that?

Thanks for using my code!

**Comment by chris-martin** [comment]
Yeah, can you add me to the project on Hackage? https://hackage.haskell.org/package/pam/maintainers/ Thanks!

**Comment by chris-martin** [comment]
Hey, any update on this?

**Comment by etarasov** [comment]
I was trying to remember my password and I finally got it.
What's your user name on hackage?

**Comment by chris-martin** [comment]
Oh, right, that's important :D

It's `chris_martin`

**Comment by etarasov** [comment]
Done. Have fun!

**Comment by chris-martin** [comment]
Thanks!

**Pull request merged**
